- task: UiPathRunJob@4
  inputs:
    orchestratorConnection: 'connectionbetorcheandazure'
    processName: 'BPA_Demo1'
    parametersFilePath: 'project.json'
    priority: 'High'
    folderName: 'karan'
    user: 'Karan CS'
    machine: 'IZD01\12784'